module.exports = {
  "parser": "babel-eslint",
  "ecmaFeatures": {
    "arrowFunctions": true,
    "blockBindings": true,
    "classes": true,
    "defaultParams": true,
    "destructuring": true,
    "experimentalObjectRestSpread": true,
    "forOf": true,
    "generators": true,
    "jsx": true,
    "modules": true,
    "objectLiteralComputedProperties": true,
    "objectLiteralDuplicateProperties": false,
    "objectLiteralShorthandMethods": true,
    "objectLiteralShorthandProperties": true,
    "regexYFlag": true,
    "regexUFlag": true,
    "spread": true,
    "superInFunctions": true,
    "templateStrings": true,
  },
  "env": {
    "browser": true,
    "es6": true,
    "jasmine": true,
    "jquery": true,
    "meteor": true,
    "mocha": true,
    "mongo": true,
    "node": true,
    "phantomjs": true,
  }
}
